ALTER TABLE IF EXISTS "Autos" RENAME TO "Auto";

ALTER TABLE IF EXISTS "Clients" RENAME TO "Client";

ALTER TABLE IF EXISTS "Elevators" RENAME TO "Elevator";

ALTER TABLE IF EXISTS "Floors" RENAME TO "Floor";

ALTER TABLE IF EXISTS "Places" RENAME TO "Place";

ALTER TABLE IF EXISTS "Tables" RENAME TO "Table";
